mgoltzsche/podman-static

- Makefile
- test/Dockerfile
- test/test-local-rootful.sh
- test/test-local-rootless.sh
- test/test-portmapping.sh
- test/test-remote.sh
Fix to Alpine versions on test to keep same as build.
> Fix alpine version to keep same as build

- Dockerfile
- Dockerfile-remote
> Update to Podman 3.2.3

- Dockerfile
* podman v3.3.0
* CNI plugins v1.0.0
* slirp4netns v1.1.12
* fuse-overlayfs v1.7.1
* crun v0.21
> Upgrade to podman 3.3.0.

- Dockerfile
- Dockerfile-remote
- Makefile
- test/remote.bats
- test/rootful.bats
- test/rootless.bats
Some internal updates to apline and bats versions. Alpine 3.14 has been released for few months now
* Update `Alpine` to 3.14
* Update `Bats` to 1.4.1
> Update to alpine and bats versions

- Dockerfile
- Dockerfile-remote
- Makefile
> Fix to #23, adding `--depth=1` option to improve checkout speed

- README.md
Minor change clarifying two system dependencies in the README.md
Resolves #28
> docs dependencies in installation section

- Dockerfile
- Makefile
Update `crun` version `1.2` to `1.3` 
Update `qemu-multiarch` version `5.2.0-2` to `6.1.0-8`
> Update `crun` and `qemu-multiarch` versions

- .github/workflows/release.yml
- .github/workflows/verify.yml
- Dockerfile
- Dockerfile-remote
- Makefile
podman 4.0.2 with updated dependencies:
* runc v1.1.0
* crun 1.4.4
* conmon v2.1.0
* CNI plugins v1.1.1
* fuse-overlayfs v1.8.2
additional changes:
* adds new `rootlessport` binary.
* use bats 1.5.0.
> update to podman v4.0.2.

- Dockerfile
- Dockerfile-remote
- Makefile
updated dependencies:
* runc 1.1.1
* crun 1.4.5
* fuse 3.11.0
> update to podman 4.1.0

- Dockerfile
- Dockerfile-remote
- Makefile
updated dependencies:
* conmon 2.1.2
* libslirp 4.7.0
* slirp4netns 1.2.0
* fuse-overlayfs 1.9
* golang 1.18
* alpine 3.15
* bats 1.7.0
> update to podman 4.1.1

- Dockerfile
- Dockerfile-remote
- Makefile
Update to Podman, CONMON, and CRUN
> Podman 4.2.0 update

- Dockerfile
- Dockerfile-remote
- podman updated 4.2.1
- runc updated to 1.1.4
- conmon updated to 2.1.4
- libfuse updated to 3.12.0
- crun updated 1.6
> Updates podman 4.2.1 and others

- Dockerfile
- Dockerfile-remote
* podman 4.4.2
* libfuse 3.14.0
> fix: bump podman v4.4.2

- Makefile
- conf/containers/containers.conf
- test/pod.yaml
- test/rootless.bats
... instead of adding catatonit
Closes #54
> fix: configure infra_image by default

- Dockerfile
- README.md
- conf/containers/containers.conf
> fix: add catatonit binary

- Dockerfile
updates:
* podman 4.4.4
* runc 1.1.5
* crun 1.8.3
* fuse 3.14.1
* fuse-overlayfs 1.11
> fix: update podman 4.4.4 and dependencies

- Dockerfile
- Dockerfile-remote
- Makefile
* podman 4.6.0
* libfuse 3.15.1
* crun 1.8.6
* alpine:3.18
(Cannot update runc yet because of https://github.com/opencontainers/runc/issues/3950.)
Closes #64
> podman 4.6.0 update

- Dockerfile
- Dockerfile-remote
updates:
* podman 4.6.2
* runc 1.1.9
* crun 1.9
* conmon 2.1.8
* slirp4netns 1.2.2
* libfuse 3.16.1
* fuseoverlayfs 1.13
> fix: bump podman 4.6.2

- Dockerfile
- Dockerfile-remote
* podman 4.8.0
* CNI plugins 1.4.0
* crun 1.12
* using go 1.20 to build binaries
> feat: upgrade podman 4.8.0 and dependencies

- Dockerfile
- Dockerfile-remote
* podman 4.8.2
* conmon 2.1.10
> upgrade podman 4.8.2

- Dockerfile
- Dockerfile-remote
* podman 4.8.3
* runc 1.1.11
* crun 1.13
Closes #77
> Upgrade 4.8.3

- Makefile
- conf/systemd/podman.service
- conf/systemd/podman.socket
I have added the files, but I don't know here I can inspect the result tar file if everything is contained correctly.
> added podman services

- README.md
> Add uninstallation steps in the README.md file

- Dockerfile
- Dockerfile-remote
Upgrade podman and dependencies:
* podman 5.2.5
* runc 1.2.1
* crun 1.18.2
* netavark 1.13.0
* aardvark-dns 1.13.1
> fix: bump podman 5.2.5

- Dockerfile
- Dockerfile-remote
Few simple updates to libraries :)
> upgrade podman=5.3.2, passt=2025_1-21.4f2c8e7, netavark=v1.13.1

- Dockerfile
- Dockerfile-remote
* podman 5.4.2
* runc 1.2.6
* crun 1.21
* netavark 1.14.1
* passt 2025_03_20.32f6212
> bump podman 5.4.2
